apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJhM0o1Ykc5MllXeGxlR1Y1T21kb2NGOWhla2RrY1c1MGRWZFhXRmszY0daV1kySk1SMXBRT0dwdVpGbDVjWEF5VmpsT2QyWT0iCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
