server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${DB_CONNECTION_STRING:jdbc:postgresql://localhost:5432/cinemaabyss}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres_password}
    driver-class-name: org.postgresql.Driver
